name: Export Interfaces And Contracts

on: [push]

jobs:
  test:
    name: Test action and scope
    # Remove the following line if you wish to export your Solidity contracts and interfaces and publish them to NPM
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Test
        # Update `my-cool-project` with your package name
        run: echo ${{ secrets.TEST_SECRET }} 